const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TF={"5m":{interval:"5m",range:"5d"},"15m":{interval:"15m",range:"1mo"},"1h":{interval:"60m",range:"3mo"},"4h":{interval:"60m",range:"6mo",aggregate:4},"1D":{interval:"1d",range:"2y"},"1W":{interval:"1wk",range:"5y"}};
const BINANCE_TF={"5m":"5m","15m":"15m","1h":"1h","4h":"4h","1D":"1d","1W":"1w"};
const state={data:[],view:90,offset:0,tf:"1D",ticker:"QQQ",source:"demo",ema20:true,ema50:true,ema200:false,bb:false,volume:true,macd:true,drag:false,lastX:0,cross:null,watch:JSON.parse(localStorage.getItem("co-watch")||'null')||["QQQ","SPY","SMH","GLD","BTC-USD","ETH-USD"],mtf:{},request:0};
const canvas=$("#chart"),ctx=canvas.getContext("2d");
const status=(text,kind="")=>{const e=$("#dataStatus");e.textContent=text;e.className="status "+kind};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function seeded(seed){let x=seed||1;return()=>((x=Math.imul(1664525,x)+1013904223>>>0)/4294967296)}
function seedData(n=320,start=100,seed=19){const rnd=seeded(seed),a=[];let p=start;for(let i=0;i<n;i++){let drift=i<75?.18:i<145?-.09:i<225?.22:.03,noise=(rnd()-.5)*2.15,o=p,c=Math.max(5,o+drift+noise),h=Math.max(o,c)+rnd()*1.5,l=Math.min(o,c)-rnd()*1.5,v=450000+rnd()*1550000;p=c;a.push({time:new Date(Date.now()-(n-i)*864e5),open:o,high:h,low:l,close:c,volume:v})}return a}
function ema(data,p,field="close"){let k=2/(p+1),out=[],v=Number(data[0]?.[field])||0;for(const d of data){v=(Number(d[field])||0)*k+v*(1-k);out.push(v)}return out}
function sma(vals,p){let out=Array(vals.length).fill(null),sum=0;for(let i=0;i<vals.length;i++){sum+=Number(vals[i])||0;if(i>=p)sum-=Number(vals[i-p])||0;if(i>=p-1)out[i]=sum/p}return out}
function stdev(vals,p){let out=Array(vals.length).fill(null);for(let i=p-1;i<vals.length;i++){let s=vals.slice(i-p+1,i+1),m=s.reduce((a,b)=>a+b,0)/p;out[i]=Math.sqrt(s.reduce((a,b)=>a+(b-m)**2,0)/p)}return out}
function bollinger(data,p=20,m=2){let c=data.map(x=>x.close),mid=sma(c,p),sd=stdev(c,p);return{mid,upper:mid.map((x,i)=>x==null?null:x+m*sd[i]),lower:mid.map((x,i)=>x==null?null:x-m*sd[i])}}
function rsi(data,p=14){let out=Array(data.length).fill(null),g=0,l=0;if(data.length<=p)return out;for(let i=1;i<=p;i++){let d=data[i].close-data[i-1].close;d>=0?g+=d:l-=d}g/=p;l/=p;out[p]=100-100/(1+g/(l||1e-9));for(let i=p+1;i<data.length;i++){let d=data[i].close-data[i-1].close;g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=100-100/(1+g/(l||1e-9))}return out}
function atr(data,p=14){let tr=data.map((d,i)=>i?Math.max(d.high-d.low,Math.abs(d.high-data[i-1].close),Math.abs(d.low-data[i-1].close)):d.high-d.low);return sma(tr,p)}
function macdCalc(data){let e12=ema(data,12),e26=ema(data,26),line=e12.map((x,i)=>x-e26[i]),fake=line.map(x=>({close:x})),signal=ema(fake,9),hist=line.map((x,i)=>x-signal[i]);return{line,signal,hist}}
function aggregate(data,n){let out=[];for(let i=0;i<data.length;i+=n){let g=data.slice(i,i+n);if(!g.length)continue;out.push({time:g[0].time,open:g[0].open,high:Math.max(...g.map(x=>x.high)),low:Math.min(...g.map(x=>x.low)),close:g.at(-1).close,volume:g.reduce((a,x)=>a+(x.volume||0),0)})}return out}
function validRows(a){return a.filter(x=>x.time instanceof Date&&!isNaN(x.time)&&[x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function cryptoSymbol(s){const m={"BTC-USD":"BTCUSDT","ETH-USD":"ETHUSDT","SOL-USD":"SOLUSDT","BNB-USD":"BNBUSDT","XRP-USD":"XRPUSDT"};return m[s]||(/^[A-Z0-9]+USDT$/.test(s)?s:null)}
async function fetchBinance(symbol,tf){let bs=cryptoSymbol(symbol);if(!bs)throw Error("not crypto");let u=`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(bs)}&interval=${BINANCE_TF[tf]}&limit=500`,r=await fetch(u);if(!r.ok)throw Error(`Binance ${r.status}`);let j=await r.json();return validRows(j.map(k=>({time:new Date(k[0]),open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]})))}
async function fetchYahooHost(host,symbol,tf){let c=TF[tf],u=`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}?interval=${c.interval}&range=${c.range}&includePrePost=false&events=div%2Csplits`,r=await fetch(u,{headers:{Accept:"application/json"}});if(!r.ok)throw Error(`Market data ${r.status}`);let j=await r.json(),z=j?.chart?.result?.[0];if(!z)throw Error(j?.chart?.error?.description||"No market data returned");let q=z.indicators?.quote?.[0]||{},rows=(z.timestamp||[]).map((t,i)=>({time:new Date(t*1000),open:+q.open?.[i],high:+q.high?.[i],low:+q.low?.[i],close:+q.close?.[i],volume:+q.volume?.[i]||0}));rows=validRows(rows);return c.aggregate?aggregate(rows,c.aggregate):rows}
async function fetchMarket(symbol,tf){let cs=cryptoSymbol(symbol);if(cs){try{return{data:await fetchBinance(symbol,tf),provider:"Binance"}}catch(e){}}
let last;for(const h of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{return{data:await fetchYahooHost(h,symbol,tf),provider:"Yahoo chart"}}catch(e){last=e}}throw last||Error("Market data unavailable")}
function bounds(data,extra=[]){let hi=Math.max(...data.map(d=>d.high)),lo=Math.min(...data.map(d=>d.low));for(const arr of extra)for(const v of arr)if(v!=null&&Number.isFinite(v)){hi=Math.max(hi,v);lo=Math.min(lo,v)}let pad=(hi-lo)*.08||1;return[lo-pad,hi+pad]}
function visible(){let end=Math.max(1,state.data.length-state.offset),start=Math.max(0,end-state.view);return{start,end,data:state.data.slice(start,end)}}
function resize(){let r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){if(!state.data.length)return;let r=canvas.getBoundingClientRect(),W=r.width,H=r.height,pad={l:12,r:64,t:30,b:30},plotW=W-pad.l-pad.r,plotH=H-pad.t-pad.b,{start,end,data}=visible();if(!data.length)return;let all=state.data,e20=ema(all,20).slice(start,end),e50=ema(all,50).slice(start,end),e200=ema(all,200).slice(start,end),bb=bollinger(all),bbu=bb.upper.slice(start,end),bbl=bb.lower.slice(start,end),extras=[];if(state.ema20)extras.push(e20);if(state.ema50)extras.push(e50);if(state.ema200)extras.push(e200);if(state.bb)extras.push(bbu,bbl);let[lo,hi]=bounds(data,extras),x=i=>pad.l+(i+.5)*plotW/data.length,y=v=>pad.t+(hi-v)/(hi-lo)*plotH;ctx.clearRect(0,0,W,H);ctx.fillStyle="#080d13";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#18232e";ctx.lineWidth=1;ctx.font="11px system-ui";ctx.fillStyle="#7d8c9b";ctx.textAlign="left";for(let i=0;i<=5;i++){let yy=pad.t+i*plotH/5,val=hi-(hi-lo)*i/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(W-pad.r,yy);ctx.stroke();ctx.fillText(formatPrice(val),W-pad.r+7,yy+4)}
if(state.volume){let maxV=Math.max(...data.map(d=>d.volume||0),1),vh=plotH*.16;data.forEach((d,i)=>{let h=(d.volume||0)/maxV*vh;ctx.globalAlpha=.22;ctx.fillStyle=d.close>=d.open?"#25c99a":"#ff6675";ctx.fillRect(x(i)-2,H-pad.b-h,4,h)});ctx.globalAlpha=1}
let cw=Math.max(2,Math.min(13,plotW/data.length*.62));data.forEach((d,i)=>{let xx=x(i),up=d.close>=d.open,col=up?"#25c99a":"#ff6675";ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(xx,y(d.high));ctx.lineTo(xx,y(d.low));ctx.stroke();let top=Math.min(y(d.open),y(d.close)),bh=Math.max(1,Math.abs(y(d.close)-y(d.open)));ctx.fillRect(xx-cw/2,top,cw,bh)});
function line(arr,col,width=1.5,dash=[]){ctx.strokeStyle=col;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let on=false;arr.forEach((v,i)=>{if(v==null)return;on?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v));on=true});ctx.stroke();ctx.setLineDash([])}if(state.ema20)line(e20,"#58a6ff");if(state.ema50)line(e50,"#f2bd54");if(state.ema200)line(e200,"#c084fc");if(state.bb){line(bbu,"#78909c",1,[4,4]);line(bbl,"#78909c",1,[4,4])}
let a=analyze(state.data);if(a.support){line(Array(data.length).fill(a.support),"#25c99a",1,[6,5])}if(a.resistance){line(Array(data.length).fill(a.resistance),"#ff6675",1,[6,5])}
if(state.cross){let ix=Math.max(0,Math.min(data.length-1,Math.floor((state.cross.x-pad.l)/(plotW/data.length)))),d=data[ix];ctx.strokeStyle="#536273";ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(state.cross.x,pad.t);ctx.lineTo(state.cross.x,H-pad.b);ctx.moveTo(pad.l,state.cross.y);ctx.lineTo(W-pad.r,state.cross.y);ctx.stroke();ctx.setLineDash([]);$("#ohlc").textContent=`${state.ticker} · ${d.time.toLocaleString()}  O ${formatPrice(d.open)} H ${formatPrice(d.high)} L ${formatPrice(d.low)} C ${formatPrice(d.close)} V ${formatVol(d.volume)}`}else $("#ohlc").textContent=`${state.ticker} · ${state.tf} · ${state.source}`}
function formatPrice(v){if(!Number.isFinite(v))return"—";return Math.abs(v)>=100? v.toFixed(2):Math.abs(v)>=1?v.toFixed(3):v.toFixed(5)}
function formatVol(v){if(!Number.isFinite(v))return"—";if(v>=1e9)return(v/1e9).toFixed(1)+"B";if(v>=1e6)return(v/1e6).toFixed(1)+"M";if(v>=1e3)return(v/1e3).toFixed(1)+"K";return Math.round(v).toString()}
function pattern(d){let l=d.at(-1),p=d.at(-2),p2=d.at(-3);if(!l||!p)return{name:"Insufficient data",bias:0,confidence:0};let body=Math.abs(l.close-l.open),range=Math.max(1e-9,l.high-l.low),lower=Math.min(l.open,l.close)-l.low,upper=l.high-Math.max(l.open,l.close);if(p2){let b2=Math.abs(p2.close-p2.open),bp=Math.abs(p.close-p.open);if(p2.close<p2.open&&bp<Math.max(b2,body)*.45&&l.close>l.open&&l.close>(p2.open+p2.close)/2)return{name:"Morning-star reversal",bias:2,confidence:88};if(p2.close>p2.open&&bp<Math.max(b2,body)*.45&&l.close<l.open&&l.close<(p2.open+p2.close)/2)return{name:"Evening-star reversal",bias:-2,confidence:88}}
if(body/range<.1)return{name:"Doji / indecision",bias:0,confidence:74};if(p.close<p.open&&l.close>l.open&&l.open<=p.close&&l.close>=p.open)return{name:"Bullish engulfing",bias:2,confidence:90};if(p.close>p.open&&l.close<l.open&&l.open>=p.close&&l.close<=p.open)return{name:"Bearish engulfing",bias:-2,confidence:90};if(lower>body*2.2&&upper<body*1.1)return{name:"Hammer-like rejection",bias:1,confidence:78};if(upper>body*2.2&&lower<body*1.1)return{name:"Shooting-star rejection",bias:-1,confidence:78};if(body/range>.78)return{name:l.close>l.open?"Bullish marubozu / impulse":"Bearish marubozu / impulse",bias:l.close>l.open?1:-1,confidence:76};return{name:"No dominant named pattern",bias:0,confidence:46}}
function swingLevels(d,n=50){let r=d.slice(-Math.min(n,d.length)),lows=[],highs=[];for(let i=2;i<r.length-2;i++){if(r[i].low<=r[i-1].low&&r[i].low<=r[i-2].low&&r[i].low<=r[i+1].low&&r[i].low<=r[i+2].low)lows.push(r[i].low);if(r[i].high>=r[i-1].high&&r[i].high>=r[i-2].high&&r[i].high>=r[i+1].high&&r[i].high>=r[i+2].high)highs.push(r[i].high)}let last=r.at(-1)?.close||0,support=Math.max(...lows.filter(x=>x<=last),Math.min(...r.map(x=>x.low))),resistance=Math.min(...highs.filter(x=>x>=last),Math.max(...r.map(x=>x.high)));if(!Number.isFinite(support))support=Math.min(...r.map(x=>x.low));if(!Number.isFinite(resistance))resistance=Math.max(...r.map(x=>x.high));return{support,resistance}}
function analyze(d){if(!d||d.length<30)return{};let e20=ema(d,20),e50=ema(d,50),e200=ema(d,200),rs=rsi(d),at=atr(d),mc=macdCalc(d),i=d.length-1,last=d[i],pat=pattern(d),{support,resistance}=swingLevels(d),score=0,evidence=[],bull=0,bear=0;
const add=(v,t)=>{score+=v;evidence.push(t);v>0?bull+=Math.abs(v):bear+=Math.abs(v)};if(last.close>e20[i])add(1,"Price is above EMA 20");else add(-1,"Price is below EMA 20");if(e20[i]>e50[i])add(2,"EMA 20 is above EMA 50");else add(-2,"EMA 20 is below EMA 50");if(i>=199){if(e50[i]>e200[i])add(1,"EMA 50 is above EMA 200");else add(-1,"EMA 50 is below EMA 200")}
let slope=(e20[i]-e20[Math.max(0,i-10)])/(Math.abs(e20[Math.max(0,i-10)])||1);if(slope>.01)add(1,"EMA 20 slope is rising");else if(slope<-.01)add(-1,"EMA 20 slope is falling");let rv=rs[i]??50;if(rv>55&&rv<72)add(1,`RSI ${rv.toFixed(0)} confirms positive momentum`);else if(rv<45&&rv>28)add(-1,`RSI ${rv.toFixed(0)} confirms negative momentum`);else if(rv>=72)add(-.5,`RSI ${rv.toFixed(0)} is stretched / overbought`);else if(rv<=28)add(.5,`RSI ${rv.toFixed(0)} is stretched / oversold`);
if(mc.hist[i]>0&&mc.line[i]>mc.signal[i])add(1,"MACD histogram is positive");else if(mc.hist[i]<0&&mc.line[i]<mc.signal[i])add(-1,"MACD histogram is negative");if(pat.bias)add(pat.bias,`${pat.name} adds ${pat.bias>0?"bullish":"bearish"} confirmation`);
let av=sma(d.map(x=>x.volume||0),20)[i]||0,vr=av?(last.volume||0)/av:0;if(vr>1.25){if(last.close>last.open)add(.75,`Volume is ${vr.toFixed(1)}× its 20-period average on an up candle`);else add(-.75,`Volume is ${vr.toFixed(1)}× its 20-period average on a down candle`)}
let range=resistance-support,pos=(last.close-support)/(range||1);if(pos<.18&&last.close>last.open)add(.75,"Price is reacting close to support");if(pos>.82&&last.close<last.open)add(-.75,"Price is rejecting close to resistance");let abs=Math.abs(score),signal=abs<2.5?"WAIT":score>0?"BUY":"SELL",conv=Math.round(Math.min(96,45+abs*6+Math.min(8,Math.abs(bull-bear)*1.8)+(pat.confidence>=80?4:0))),trend=e20[i]>e50[i]?(slope>0?"Bullish":"Bullish / flattening"):(slope<0?"Bearish":"Bearish / flattening"),atrv=at[i]||last.close*.02,entry=last.close,stop=null,target1=null,target2=null;if(signal==="BUY"){stop=Math.min(support,entry-1.25*atrv);let risk=entry-stop;target1=entry+risk*2;target2=entry+risk*3}else if(signal==="SELL"){stop=Math.max(resistance,entry+1.25*atrv);let risk=stop-entry;target1=entry-risk*2;target2=entry-risk*3}let invalid=signal==="BUY"?`A sustained break below ${formatPrice(stop)} invalidates this bullish setup.`:signal==="SELL"?`A sustained recovery above ${formatPrice(stop)} invalidates this bearish setup.`:"Wait for a decisive break of support/resistance or stronger indicator alignment.";return{signal,conv,score,bull,bear,pattern:pat.name,patternConfidence:pat.confidence,rsi:rv,ema20:e20[i],ema50:e50[i],ema200:e200[i],support,resistance,entry,stop,target1,target2,rr:2,evidence,trend,atr:atrv,macd:mc.line[i],macdSignal:mc.signal[i],macdHist:mc.hist[i],volumeRatio:vr,invalid}}
function renderAnalysis(){let a=analyze(state.data);if(!a.signal)return;let cls=a.signal.toLowerCase(),why=a.signal==="WAIT"?"No sufficiently strong multi-factor edge is present.":a.signal==="BUY"?"Bullish technical factors currently outweigh bearish factors.":"Bearish technical factors currently outweigh bullish factors.";$("#analysis").innerHTML=`<div class="decision ${cls}"><div class="eyebrow">Chart decision · ${state.tf}</div><h1>${a.signal}</h1><div>${why}</div><div class="confidence"><strong>${a.conv}%</strong><span>overall conviction</span></div></div><div class="section"><h3>Signal quality</h3><div class="scoreGrid"><div class="scoreBox"><small>Bull evidence</small><b>${a.bull.toFixed(1)}</b></div><div class="scoreBox"><small>Bear evidence</small><b>${a.bear.toFixed(1)}</b></div></div></div><div class="section"><h3>Read</h3><div class="row"><span>Trend</span><b>${a.trend}</b></div><div class="row"><span>Pattern</span><b>${a.pattern}</b></div><div class="row"><span>Pattern confidence</span><b>${a.patternConfidence}%</b></div><div class="row"><span>RSI 14</span><b>${a.rsi.toFixed(1)}</b></div><div class="row"><span>MACD histogram</span><b>${a.macdHist.toFixed(3)}</b></div></div><div class="section"><h3>Trade framing</h3>${a.signal==="WAIT"?`<div class="evidence">${a.invalid}</div>`:`<div class="planGrid"><div class="planBox"><small>Entry reference</small><b>${formatPrice(a.entry)}</b></div><div class="planBox"><small>Invalidation</small><b>${formatPrice(a.stop)}</b></div><div class="planBox"><small>Target 1 · 2R</small><b>${formatPrice(a.target1)}</b></div><div class="planBox"><small>Target 2 · 3R</small><b>${formatPrice(a.target2)}</b></div></div><div class="evidence">${a.invalid}</div>`}</div><div class="section"><h3>Evidence</h3>${a.evidence.map(x=>`<div class="evidence">${x}</div>`).join("")}</div><div class="section"><h3>Key levels</h3><div class="row"><span>Support</span><b>${formatPrice(a.support)}</b></div><div class="row"><span>Resistance</span><b>${formatPrice(a.resistance)}</b></div><div class="row"><span>ATR 14</span><b>${formatPrice(a.atr)}</b></div></div>`;$("#rsiVal").textContent=a.rsi.toFixed(1);$("#rsiMeter").style.width=Math.max(0,Math.min(100,a.rsi))+"%";$("#trendText").textContent=a.trend;$("#patternText").textContent=a.pattern;$("#atrText").textContent=formatPrice(a.atr);$("#macdText").textContent=`${a.macd.toFixed(3)} / signal ${a.macdSignal.toFixed(3)}`;$("#volumeText").textContent=a.volumeRatio?`${a.volumeRatio.toFixed(2)}×`:"N/A"}
function saveWatch(){localStorage.setItem("co-watch",JSON.stringify(state.watch));renderWatch()}
function renderWatch(){let w=$("#watchlist");w.innerHTML=state.watch.map(s=>`<div class="watchItem ${s===state.ticker?"active":""}" data-sym="${s}"><b>${s}</b><span>load</span></div>`).join("");w.querySelectorAll(".watchItem").forEach(x=>x.onclick=()=>loadSymbol(x.dataset.sym))}
async function loadSymbol(sym=state.ticker,{quiet=false,mtf=true}={}){sym=(sym||"").trim().toUpperCase();if(!sym)return;let id=++state.request;state.ticker=sym;$("#ticker").value=sym;if(!quiet)status(`Loading ${sym} ${state.tf}…`);try{let r=await fetchMarket(sym,state.tf);if(id!==state.request&&!quiet)return;state.data=r.data;state.source=r.provider;state.offset=0;state.view=Math.min(110,state.data.length);if(!quiet){status(`${r.provider} · ${state.data.length} candles`,"ok");renderAnalysis();draw();renderWatch();if(mtf)updateMTF(sym)}}catch(e){if(!quiet){status(`Live data blocked: ${e.message}`,"err");state.data=seedData(320,100,Math.abs([...sym].reduce((a,c)=>a+c.charCodeAt(0),0)));state.source="Demo fallback";state.offset=0;renderAnalysis();draw();renderWatch();$("#analysis").insertAdjacentHTML("afterbegin",`<div class="evidence" style="margin:14px">Live/delayed provider access failed in this browser. Demo fallback is shown. Import OHLC CSV for verified prices.</div>`)}}}
async function updateMTF(sym){state.mtf={};renderMTF();let frames=["5m","15m","1h","4h","1D","1W"];for(const tf of frames){try{let r=tf===state.tf?{data:state.data}:await fetchMarket(sym,tf),a=analyze(r.data);state.mtf[tf]=a.signal||"—"}catch(e){state.mtf[tf]="—"}renderMTF();await sleep(90)}}
function renderMTF(){let el=$("#mtf"),frames=["5m","15m","1h","4h","1D","1W"];el.innerHTML=frames.map(tf=>{let s=state.mtf[tf]||"—",c=s==="BUY"?"buy":s==="SELL"?"sell":s==="WAIT"?"wait":"";return`<span class="${c}">${tf} ${s}</span>`}).join("")}
async function scanWatch(){let btn=$("#scanBtn");btn.disabled=true;$("#scanner").innerHTML='<div class="muted small">Scanning…</div>';let out=[];for(let i=0;i<state.watch.length;i+=3){let batch=state.watch.slice(i,i+3);let rr=await Promise.all(batch.map(async s=>{try{let r=await fetchMarket(s,state.tf),a=analyze(r.data);return{s,signal:a.signal,conv:a.conv||0}}catch(e){return{s,signal:"—",conv:0}}}));out.push(...rr);renderScanner(out);await sleep(120)}out.sort((a,b)=>b.conv-a.conv);renderScanner(out);btn.disabled=false}
function renderScanner(rows){$("#scanner").innerHTML=rows.map(x=>`<div class="scanRow" data-sym="${x.s}"><b>${x.s}</b><b class="${x.signal==="BUY"?"sigBuy":x.signal==="SELL"?"sigSell":"sigWait"}">${x.signal}</b><span>${x.conv?x.conv+"%":"—"}</span></div>`).join("");$("#scanner").querySelectorAll(".scanRow").forEach(x=>x.onclick=()=>loadSymbol(x.dataset.sym))}
function parseCSV(text){let lines=text.trim().split(/\r?\n/),head=lines.shift().split(",").map(x=>x.trim().toLowerCase()),idx=n=>head.indexOf(n),required=["open","high","low","close"];if(required.some(n=>idx(n)<0))throw Error("CSV needs open, high, low and close columns.");let out=lines.map((l,k)=>{let c=l.split(","),ti=idx("time")>=0?idx("time"):idx("date"),t=ti>=0?new Date(c[ti]):new Date(Date.now()-(lines.length-k)*864e5);return{time:t,open:+c[idx("open")],high:+c[idx("high")],low:+c[idx("low")],close:+c[idx("close")],volume:idx("volume")>=0?+c[idx("volume")]:0}});out=validRows(out);if(out.length<30)throw Error("Please provide at least 30 valid candles.");return out}
$("#csv").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{state.data=parseCSV(await f.text());state.ticker=f.name.replace(/\.csv$/i,"").toUpperCase();state.source="CSV";state.offset=0;state.view=Math.min(110,state.data.length);$("#ticker").value=state.ticker;status(`CSV · ${state.data.length} candles`,"ok");renderAnalysis();draw();renderWatch()}catch(err){status(err.message,"err")}};
$("#loadTicker").onclick=()=>loadSymbol($("#ticker").value);$("#ticker").addEventListener("keydown",e=>{if(e.key==="Enter")loadSymbol(e.target.value)});$("#demo").onclick=()=>{state.data=seedData();state.ticker="DEMO";state.source="Demo";state.offset=0;state.view=90;$("#ticker").value="DEMO";status("Deterministic demo data","ok");renderAnalysis();draw();renderWatch();state.mtf={};renderMTF()};$("#uploadBtn").onclick=()=>$("#csv").click();$("#scanBtn").onclick=scanWatch;$("#addWatch").onclick=()=>{let s=prompt("Add ticker to watchlist (e.g. QQQ, GLD, BTC-USD)");if(!s)return;s=s.trim().toUpperCase();if(s&&!state.watch.includes(s)){state.watch.push(s);saveWatch()}};
$$('.tf').forEach(b=>b.onclick=async()=>{$$('.tf').forEach(x=>x.classList.remove("active"));b.classList.add("active");state.tf=b.dataset.tf;if(state.ticker!=="DEMO"&&state.source!=="CSV"&&state.source!=="Demo fallback")await loadSymbol(state.ticker);else{renderAnalysis();draw()}});$$('[data-ind]').forEach(b=>b.onclick=()=>{let k=b.dataset.ind;state[k]=!state[k];b.classList.toggle("primary",state[k]);draw()});
canvas.addEventListener("wheel",e=>{e.preventDefault();state.view=Math.max(25,Math.min(state.data.length,state.view+(e.deltaY>0?10:-10)));draw()},{passive:false});canvas.addEventListener("mousedown",e=>{state.drag=true;state.lastX=e.clientX});window.addEventListener("mouseup",()=>state.drag=false);window.addEventListener("mousemove",e=>{let r=canvas.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)state.cross={x:e.clientX-r.left,y:e.clientY-r.top};else state.cross=null;if(state.drag){let dx=e.clientX-state.lastX;if(Math.abs(dx)>8){state.offset=Math.max(0,Math.min(Math.max(0,state.data.length-state.view),state.offset+(dx>0?2:-2)));state.lastX=e.clientX}}draw()});canvas.addEventListener("mouseleave",()=>{if(!state.drag){state.cross=null;draw()}});window.addEventListener("resize",resize);
renderWatch();state.data=seedData();renderAnalysis();renderMTF();requestAnimationFrame(resize);loadSymbol("QQQ");