function saveWatch(){localStorage.setItem("co-watch",JSON.stringify(state.watch));renderWatch()}
function renderWatch(){let w=$("#watchlist");w.innerHTML=state.watch.map(s=>`<div class="watchItem ${s===state.ticker?"active":""}" data-sym="${s}"><b>${s}</b><span>load</span></div>`).join("");w.querySelectorAll(".watchItem").forEach(x=>x.onclick=()=>loadSymbol(x.dataset.sym))}
async function loadSymbol(sym=state.ticker,{quiet=false,mtf=true}={}){sym=(sym||"").trim().toUpperCase();if(!sym)return;let id=++state.request;state.ticker=sym;$("#ticker").value=sym;if(!quiet)status(`Loading ${sym} ${state.tf}…`);try{let r=await fetchMarket(sym,state.tf);if(id!==state.request&&!quiet)return;state.data=r.data;state.source=r.provider;state.offset=0;state.view=Math.min(110,state.data.length);if(!quiet){setProviderChip(r.provider);status(`${r.provider} · ${state.data.length} candles`,"ok");renderAnalysis();draw();renderWatch();if(mtf)updateMTF(sym)}}catch(e){if(!quiet){status(`Live data blocked: ${e.message}`,"err");state.data=seedData(320,100,Math.abs([...sym].reduce((a,c)=>a+c.charCodeAt(0),0)));state.source="Demo fallback";setProviderChip("Demo");state.offset=0;renderAnalysis();draw();renderWatch();$("#analysis").insertAdjacentHTML("afterbegin",`<div class="evidence" style="margin:14px">Live/delayed provider access failed (proxy + public fallbacks). Demo fallback is shown. Import OHLC CSV for verified prices, or start the candle proxy on localhost:5055.</div>`)}}}
async function updateMTF(sym){state.mtf={};renderMTF();let frames=["5m","15m","1h","4h","1D","1W"];for(const tf of frames){try{let r=tf===state.tf?{data:state.data}:await fetchMarket(sym,tf),a=analyze(r.data);state.mtf[tf]=a.signal||"—"}catch(e){state.mtf[tf]="—"}renderMTF();await sleep(90)}}
function renderMTF(){let el=$("#mtf"),frames=["5m","15m","1h","4h","1D","1W"];el.innerHTML=frames.map(tf=>{let s=state.mtf[tf]||"—",c=s==="BUY"?"buy":s==="SELL"?"sell":s==="WAIT"?"wait":"";return`<span class="${c}">${tf} ${s}</span>`}).join("")}
async function scanWatch(){let btn=$("#scanBtn");btn.disabled=true;$("#scanner").innerHTML='<div class="muted small">Scanning…</div>';let out=[];for(let i=0;i<state.watch.length;i+=3){let batch=state.watch.slice(i,i+3);let rr=await Promise.all(batch.map(async s=>{try{let r=await fetchMarket(s,state.tf),a=analyze(r.data);return{s,signal:a.signal,conv:a.conv||0}}catch(e){return{s,signal:"—",conv:0}}}));out.push(...rr);renderScanner(out);await sleep(120)}out.sort((a,b)=>b.conv-a.conv);renderScanner(out);btn.disabled=false}
function renderScanner(rows){$("#scanner").innerHTML=rows.map(x=>`<div class="scanRow" data-sym="${x.s}"><b>${x.s}</b><b class="${x.signal==="BUY"?"sigBuy":x.signal==="SELL"?"sigSell":"sigWait"}">${x.signal}</b><span>${x.conv?x.conv+"%":"—"}</span></div>`).join("");$("#scanner").querySelectorAll(".scanRow").forEach(x=>x.onclick=()=>loadSymbol(x.dataset.sym))}
function parseCSV(text){let lines=text.trim().split(/\r?\n/),head=lines.shift().split(",").map(x=>x.trim().toLowerCase()),idx=n=>head.indexOf(n),required=["open","high","low","close"];if(required.some(n=>idx(n)<0))throw Error("CSV needs open, high, low and close columns.");let out=lines.map((l,k)=>{let c=l.split(","),ti=idx("time")>=0?idx("time"):idx("date"),t=ti>=0?new Date(c[ti]):new Date(Date.now()-(lines.length-k)*864e5);return{time:t,open:+c[idx("open")],high:+c[idx("high")],low:+c[idx("low")],close:+c[idx("close")],volume:idx("volume")>=0?+c[idx("volume")]:0}});out=validRows(out);if(out.length<30)throw Error("Please provide at least 30 valid candles.");return out}
$("#csv").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{state.data=parseCSV(await f.text());state.ticker=f.name.replace(/\.csv$/i,"").toUpperCase();state.source="CSV";state.offset=0;state.view=Math.min(110,state.data.length);$("#ticker").value=state.ticker;setProviderChip("CSV");status(`CSV · ${state.data.length} candles`,"ok");renderAnalysis();draw();renderWatch()}catch(err){status(err.message,"err")}};
$("#loadTicker").onclick=()=>loadSymbol($("#ticker").value);$("#ticker").addEventListener("keydown",e=>{if(e.key==="Enter")loadSymbol(e.target.value)});$("#demo").onclick=()=>{state.data=seedData();state.ticker="DEMO";state.source="Demo";state.offset=0;state.view=90;$("#ticker").value="DEMO";setProviderChip("Demo");status("Deterministic demo data","ok");renderAnalysis();draw();renderWatch();state.mtf={};renderMTF()};$("#uploadBtn").onclick=()=>$("#csv").click();$("#scanBtn").onclick=scanWatch;$("#addWatch").onclick=()=>{let s=prompt("Add ticker to watchlist (e.g. QQQ, GLD, BTC-USD)");if(!s)return;s=s.trim().toUpperCase();if(s&&!state.watch.includes(s)){state.watch.push(s);saveWatch()}};
$$('.tf').forEach(b=>b.onclick=async()=>{$$('.tf').forEach(x=>x.classList.remove("active"));b.classList.add("active");state.tf=b.dataset.tf;if(state.ticker!=="DEMO"&&state.source!=="CSV"&&state.source!=="Demo fallback")await loadSymbol(state.ticker);else{renderAnalysis();draw()}});$$('[data-ind]').forEach(b=>b.onclick=()=>{let k=b.dataset.ind;state[k]=!state[k];b.classList.toggle("primary",state[k]);draw()});
canvas.addEventListener("wheel",e=>{e.preventDefault();state.view=Math.max(25,Math.min(state.data.length,state.view+(e.deltaY>0?10:-10)));draw()},{passive:false});canvas.addEventListener("mousedown",e=>{state.drag=true;state.lastX=e.clientX});window.addEventListener("mouseup",()=>state.drag=false);window.addEventListener("mousemove",e=>{let r=canvas.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)state.cross={x:e.clientX-r.left,y:e.clientY-r.top};else state.cross=null;if(state.drag){let dx=e.clientX-state.lastX;if(Math.abs(dx)>8){state.offset=Math.max(0,Math.min(Math.max(0,state.data.length-state.view),state.offset+(dx>0?2:-2)));state.lastX=e.clientX}}draw()});canvas.addEventListener("mouseleave",()=>{if(!state.drag){state.cross=null;draw()}});window.addEventListener("resize",resize);
function sendToAnalysis(){if(!state.data||state.data.length<7){status("Need at least 7 candles to send","err");return}const payload={symbol:state.ticker,interval:state.tf,provider:state.source,candles:state.data.map(d=>({time:d.time instanceof Date?d.time.toISOString():String(d.time),open:d.open,high:d.high,low:d.low,close:d.close,volume:d.volume||0})),savedAt:new Date().toISOString()};try{sessionStorage.setItem(LIVE_CANDLES_KEY,JSON.stringify(payload));localStorage.setItem(LIVE_CANDLES_KEY,JSON.stringify(payload))}catch(e){status("Could not store candles for analysis","err");return}status(`Sent ${payload.candles.length} candles → analysis`,"ok");location.href="index.html?live=1"}
(function initApiBase(){const el=$("#apiBase");if(!el)return;el.value=resolveApiBase();el.addEventListener("change",()=>{const v=el.value.trim().replace(/\/$/,"");if(v){localStorage.setItem("co-api-base",v);status(`API base → ${v}`,"ok")}});const send=$("#sendAnalysis");if(send)send.onclick=sendToAnalysis})();
renderWatch();state.data=seedData();renderAnalysis();renderMTF();requestAnimationFrame(resize);loadSymbol("QQQ");
