const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={data:[],view:90,offset:0,tf:'1D',ticker:'DEMO',ema20:true,ema50:true,ema200:false,bb:false,drag:false,lastX:0,cross:null};
const canvas=$('#chart'),ctx=canvas.getContext('2d');
function seedData(n=260,start=100){let a=[],p=start;for(let i=0;i<n;i++){let drift=(i<70?.22:i<130?-.08:i<185?.3:-.02),noise=(Math.random()-.5)*2.2,o=p,c=Math.max(5,o+drift+noise),h=Math.max(o,c)+Math.random()*1.4,l=Math.min(o,c)-Math.random()*1.4,v=500000+Math.random()*1300000;p=c;a.push({time:new Date(Date.now()-(n-i)*864e5),open:o,high:h,low:l,close:c,volume:v})}return a}
function ema(data,p){let k=2/(p+1),out=[],v=data[0]?.close||0;for(let d of data){v=d.close*k+v*(1-k);out.push(v)}return out}
function sma(vals,p){return vals.map((_,i)=>i<p-1?null:vals.slice(i-p+1,i+1).reduce((a,b)=>a+b,0)/p)}
function rsi(data,p=14){let out=Array(data.length).fill(null),g=0,l=0;for(let i=1;i<=p&&i<data.length;i++){let d=data[i].close-data[i-1].close;d>=0?g+=d:l-=d}if(data.length<=p)return out;g/=p;l/=p;out[p]=100-(100/(1+(g/(l||1e-9))));for(let i=p+1;i<data.length;i++){let d=data[i].close-data[i-1].close,up=Math.max(d,0),dn=Math.max(-d,0);g=(g*(p-1)+up)/p;l=(l*(p-1)+dn)/p;out[i]=100-(100/(1+(g/(l||1e-9))))}return out}
function atr(data,p=14){let tr=data.map((d,i)=>i?Math.max(d.high-d.low,Math.abs(d.high-data[i-1].close),Math.abs(d.low-data[i-1].close)):d.high-d.low);let s=sma(tr,p);return s}
function bounds(data,extra=[]){let hi=Math.max(...data.map(d=>d.high)),lo=Math.min(...data.map(d=>d.low));for(let arr of extra)for(let v of arr)if(v!=null){hi=Math.max(hi,v);lo=Math.min(lo,v)}let pad=(hi-lo)*.08||1;return[lo-pad,hi+pad]}
function resize(){let r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.floor(r.width*dpr);canvas.height=Math.floor(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function visible(){let end=Math.max(1,state.data.length-state.offset),start=Math.max(0,end-state.view);return{start,end,data:state.data.slice(start,end)}}
function draw(){if(!state.data.length)return;let r=canvas.getBoundingClientRect(),W=r.width,H=r.height,pad={l:12,r:62,t:28,b:28},plotW=W-pad.l-pad.r,plotH=H-pad.t-pad.b,{start,end,data}=visible();let e20=ema(state.data,20).slice(start,end),e50=ema(state.data,50).slice(start,end),e200=ema(state.data,200).slice(start,end),extras=[];if(state.ema20)extras.push(e20);if(state.ema50)extras.push(e50);if(state.ema200)extras.push(e200);let[lo,hi]=bounds(data,extras),x=i=>pad.l+(i+.5)*plotW/data.length,y=v=>pad.t+(hi-v)/(hi-lo)*plotH;ctx.clearRect(0,0,W,H);ctx.fillStyle='#080d13';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#18232e';ctx.lineWidth=1;ctx.font='11px system-ui';ctx.fillStyle='#7d8c9b';ctx.textAlign='left';for(let i=0;i<=5;i++){let yy=pad.t+i*plotH/5,val=hi-(hi-lo)*i/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(W-pad.r,yy);ctx.stroke();ctx.fillText(val.toFixed(2),W-pad.r+8,yy+4)}let cw=Math.max(2,plotW/data.length*.62);data.forEach((d,i)=>{let xx=x(i),up=d.close>=d.open,col=up?'#25c99a':'#ff6675';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(xx,y(d.high));ctx.lineTo(xx,y(d.low));ctx.stroke();let top=Math.min(y(d.open),y(d.close)),bh=Math.max(1,Math.abs(y(d.close)-y(d.open)));ctx.fillRect(xx-cw/2,top,cw,bh)});
function line(arr,col){ctx.strokeStyle=col;ctx.lineWidth=1.5;ctx.beginPath();let on=false;arr.forEach((v,i)=>{if(v==null)return;let xx=x(i),yy=y(v);on?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);on=true});ctx.stroke()}if(state.ema20)line(e20,'#58a6ff');if(state.ema50)line(e50,'#f2bd54');if(state.ema200)line(e200,'#c084fc');
let a=analyze();if(a.support){ctx.setLineDash([6,5]);ctx.strokeStyle='#25c99a';ctx.beginPath();ctx.moveTo(pad.l,y(a.support));ctx.lineTo(W-pad.r,y(a.support));ctx.stroke()}if(a.resistance){ctx.strokeStyle='#ff6675';ctx.beginPath();ctx.moveTo(pad.l,y(a.resistance));ctx.lineTo(W-pad.r,y(a.resistance));ctx.stroke()}ctx.setLineDash([]);
if(state.cross){let ix=Math.max(0,Math.min(data.length-1,Math.floor((state.cross.x-pad.l)/(plotW/data.length)))),d=data[ix];ctx.strokeStyle='#536273';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(state.cross.x,pad.t);ctx.lineTo(state.cross.x,H-pad.b);ctx.moveTo(pad.l,state.cross.y);ctx.lineTo(W-pad.r,state.cross.y);ctx.stroke();ctx.setLineDash([]);$('#ohlc').textContent=`${d.time.toLocaleDateString()}  O ${d.open.toFixed(2)}  H ${d.high.toFixed(2)}  L ${d.low.toFixed(2)}  C ${d.close.toFixed(2)}  V ${Math.round(d.volume).toLocaleString()}`}else{$('#ohlc').textContent=`${state.ticker} · ${state.tf}`}}
function pattern(data){let l=data.at(-1),p=data.at(-2);if(!l||!p)return{name:'Insufficient data',bias:0,confidence:0};let body=Math.abs(l.close-l.open),range=l.high-l.low,pr=Math.abs(p.close-p.open);if(range&&body/range<.12)return{name:'Doji / indecision',bias:0,confidence:58};if(p.close<p.open&&l.close>l.open&&l.open<=p.close&&l.close>=p.open)return{name:'Bullish engulfing',bias:2,confidence:86};if(p.close>p.open&&l.close<l.open&&l.open>=p.close&&l.close<=p.open)return{name:'Bearish engulfing',bias:-2,confidence:86};let lower=Math.min(l.open,l.close)-l.low,upper=l.high-Math.max(l.open,l.close);if(lower>body*2.2&&upper<body)return{name:'Hammer-like rejection',bias:1,confidence:72};if(upper>body*2.2&&lower<body)return{name:'Shooting-star rejection',bias:-1,confidence:72};if(body/range>.72)return{name:l.close>l.open?'Bullish impulse candle':'Bearish impulse candle',bias:l.close>l.open?1:-1,confidence:68};return{name:'No dominant named pattern',bias:0,confidence:42}}
function analyze(){let d=state.data;if(d.length<30)return{};let closes=d.map(x=>x.close),e20=ema(d,20),e50=ema(d,50),r=rsi(d),at=atr(d),last=d.at(-1),i=d.length-1,recent=d.slice(-35),support=Math.min(...recent.map(x=>x.low)),resistance=Math.max(...recent.map(x=>x.high)),pat=pattern(d),score=0,evidence=[];if(last.close>e20[i]){score+=1;evidence.push('Price is above EMA 20')}else{score-=1;evidence.push('Price is below EMA 20')}if(e20[i]>e50[i]){score+=2;evidence.push('EMA 20 is above EMA 50')}else{score-=2;evidence.push('EMA 20 is below EMA 50')}let slope=(e20[i]-e20[Math.max(0,i-10)])/(Math.abs(e20[Math.max(0,i-10)])||1);if(slope>.01){score+=1;evidence.push('EMA 20 slope is rising')}else if(slope<-.01){score-=1;evidence.push('EMA 20 slope is falling')}let rv=r[i]||50;if(rv>55&&rv<72){score+=1;evidence.push(`RSI ${rv.toFixed(0)} supports bullish momentum`)}else if(rv<45&&rv>28){score-=1;evidence.push(`RSI ${rv.toFixed(0)} supports bearish momentum`)}else if(rv>=72){score-=.5;evidence.push(`RSI ${rv.toFixed(0)} is stretched / overbought`)}else if(rv<=28){score+=.5;evidence.push(`RSI ${rv.toFixed(0)} is stretched / oversold`)}score+=pat.bias;pat.bias&&evidence.push(`${pat.name} adds ${pat.bias>0?'bullish':'bearish'} confirmation`);let range=resistance-support,pos=(last.close-support)/(range||1);if(pos<.22&&last.close>last.open){score+=1;evidence.push('Price is reacting near visible support')}if(pos>.78&&last.close<last.open){score-=1;evidence.push('Price is rejecting near visible resistance')}let abs=Math.abs(score),signal=abs<2?'WAIT':score>0?'BUY':'SELL',conv=Math.round(Math.min(94,48+abs*8+(pat.confidence>70?5:0))),atrv=at[i]||last.close*.02,entry=last.close,stop=signal==='BUY'?Math.min(support,entry-1.35*atrv):signal==='SELL'?Math.max(resistance,entry+1.35*atrv):null,risk=stop?Math.abs(entry-stop):null,target=signal==='BUY'?entry+risk*2:signal==='SELL'?entry-risk*2:null;return{signal,conv,score,pattern:pat.name,patternConfidence:pat.confidence,rsi:rv,ema20:e20[i],ema50:e50[i],support,resistance,entry,stop,target,rr:target?2:null,evidence,trend:e20[i]>e50[i]?'Bullish':'Bearish'}}
function renderAnalysis(){let a=analyze();if(!a.signal)return;let cls=a.signal.toLowerCase(),why=a.signal==='WAIT'?'Evidence is mixed or insufficiently aligned.':a.signal==='BUY'?'Bullish factors currently outweigh bearish factors.':'Bearish factors currently outweigh bullish factors.';$('#analysis').innerHTML=`<div class="decision ${cls}"><div class="eyebrow">Chart decision</div><h1>${a.signal}</h1><div>${why}</div><div class="confidence"><strong>${a.conv}%</strong><span>overall conviction</span></div></div><div class="section"><h3>Read</h3><div class="row"><span>Trend</span><b>${a.trend}</b></div><div class="row"><span>Pattern</span><b>${a.pattern}</b></div><div class="row"><span>Pattern confidence</span><b>${a.patternConfidence}%</b></div><div class="row"><span>RSI 14</span><b>${a.rsi.toFixed(1)}</b></div><div class="row"><span>EMA 20 / 50</span><b>${a.ema20.toFixed(2)} / ${a.ema50.toFixed(2)}</b></div></div><div class="section"><h3>Trade framing</h3>${a.signal==='WAIT'?'<div class="evidence">Wait for a confirmed range break or stronger multi-factor alignment before framing a directional setup.</div>':`<div class="planGrid"><div class="planBox"><small>Entry reference</small><b>${a.entry.toFixed(2)}</b></div><div class="planBox"><small>Invalidation</small><b>${a.stop.toFixed(2)}</b></div><div class="planBox"><small>Target 1</small><b>${a.target.toFixed(2)}</b></div><div class="planBox"><small>Risk : reward</small><b>1 : ${a.rr.toFixed(1)}</b></div></div>`}</div><div class="section"><h3>Evidence</h3>${a.evidence.map(x=>`<div class="evidence">${x}</div>`).join('')}</div><div class="section"><h3>Key levels</h3><div class="row"><span>Support</span><b>${a.support.toFixed(2)}</b></div><div class="row"><span>Resistance</span><b>${a.resistance.toFixed(2)}</b></div></div>`;$('#rsiVal').textContent=a.rsi.toFixed(1);$('#rsiMeter').style.width=Math.max(0,Math.min(100,a.rsi))+'%';$('#trendText').textContent=a.trend;$('#patternText').textContent=a.pattern}
function loadDemo(){state.data=seedData();state.ticker='DEMO';state.offset=0;$('#ticker').value='DEMO';renderAnalysis();draw()}
function parseCSV(text){let lines=text.trim().split(/\r?\n/),head=lines.shift().split(',').map(x=>x.trim().toLowerCase()),idx=n=>head.indexOf(n),required=['open','high','low','close'];if(required.some(n=>idx(n)<0))throw Error('CSV needs open, high, low and close columns.');let out=lines.map((l,k)=>{let c=l.split(',');let t=idx('time')>=0?new Date(c[idx('time')]):new Date(Date.now()-(lines.length-k)*864e5);return{time:t,open:+c[idx('open')],high:+c[idx('high')],low:+c[idx('low')],close:+c[idx('close')],volume:idx('volume')>=0?+c[idx('volume')]:0}}).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite));if(out.length<30)throw Error('Please provide at least 30 valid candles.');return out}
$('#csv').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{state.data=parseCSV(await f.text());state.ticker=f.name.replace(/\.csv$/i,'').toUpperCase();$('#ticker').value=state.ticker;state.offset=0;renderAnalysis();draw()}catch(err){alert(err.message)}};
$('#ticker').addEventListener('change',e=>{state.ticker=e.target.value.trim().toUpperCase()||'DEMO';renderAnalysis();draw()});
$$('.tf').forEach(b=>b.onclick=()=>{$$('.tf').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tf=b.dataset.tf;draw()});
$$('[data-ind]').forEach(b=>b.onclick=()=>{let k=b.dataset.ind;state[k]=!state[k];b.classList.toggle('primary',state[k]);draw()});
$('#demo').onclick=loadDemo;$('#uploadBtn').onclick=()=>$('#csv').click();
canvas.addEventListener('wheel',e=>{e.preventDefault();state.view=Math.max(25,Math.min(state.data.length,state.view+(e.deltaY>0?10:-10)));draw()},{passive:false});
canvas.addEventListener('mousedown',e=>{state.drag=true;state.lastX=e.clientX});window.addEventListener('mouseup',()=>state.drag=false);window.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)state.cross={x:e.clientX-r.left,y:e.clientY-r.top};else state.cross=null;if(state.drag){let dx=e.clientX-state.lastX;if(Math.abs(dx)>8){state.offset=Math.max(0,Math.min(state.data.length-state.view,state.offset+(dx>0?2:-2)));state.lastX=e.clientX}}draw()});canvas.addEventListener('mouseleave',()=>{if(!state.drag){state.cross=null;draw()}});window.addEventListener('resize',resize);loadDemo();requestAnimationFrame(resize);