function bounds(data,extra=[]){let hi=Math.max(...data.map(d=>d.high)),lo=Math.min(...data.map(d=>d.low));for(const arr of extra)for(const v of arr)if(v!=null&&Number.isFinite(v)){hi=Math.max(hi,v);lo=Math.min(lo,v)}let pad=(hi-lo)*.08||1;return[lo-pad,hi+pad]}
function visible(){let end=Math.max(1,state.data.length-state.offset),start=Math.max(0,end-state.view);return{start,end,data:state.data.slice(start,end)}}
function resize(){let r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){if(!state.data.length)return;let r=canvas.getBoundingClientRect(),W=r.width,H=r.height,pad={l:12,r:64,t:30,b:30},plotW=W-pad.l-pad.r,plotH=H-pad.t-pad.b,{start,end,data}=visible();if(!data.length)return;let all=state.data,e20=ema(all,20).slice(start,end),e50=ema(all,50).slice(start,end),e200=ema(all,200).slice(start,end),bb=bollinger(all),bbu=bb.upper.slice(start,end),bbl=bb.lower.slice(start,end),extras=[];if(state.ema20)extras.push(e20);if(state.ema50)extras.push(e50);if(state.ema200)extras.push(e200);if(state.bb)extras.push(bbu,bbl);let[lo,hi]=bounds(data,extras),x=i=>pad.l+(i+.5)*plotW/data.length,y=v=>pad.t+(hi-v)/(hi-lo)*plotH;ctx.clearRect(0,0,W,H);ctx.fillStyle="#080d13";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#18232e";ctx.lineWidth=1;ctx.font="11px system-ui";ctx.fillStyle="#7d8c9b";ctx.textAlign="left";for(let i=0;i<=5;i++){let yy=pad.t+i*plotH/5,val=hi-(hi-lo)*i/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(W-pad.r,yy);ctx.stroke();ctx.fillText(formatPrice(val),W-pad.r+7,yy+4)}
if(state.volume){let maxV=Math.max(...data.map(d=>d.volume||0),1),vh=plotH*.16;data.forEach((d,i)=>{let h=(d.volume||0)/maxV*vh;ctx.globalAlpha=.22;ctx.fillStyle=d.close>=d.open?"#25c99a":"#ff6675";ctx.fillRect(x(i)-2,H-pad.b-h,4,h)});ctx.globalAlpha=1}
let cw=Math.max(2,Math.min(13,plotW/data.length*.62));data.forEach((d,i)=>{let xx=x(i),up=d.close>=d.open,col=up?"#25c99a":"#ff6675";ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(xx,y(d.high));ctx.lineTo(xx,y(d.low));ctx.stroke();let top=Math.min(y(d.open),y(d.close)),bh=Math.max(1,Math.abs(y(d.close)-y(d.open)));ctx.fillRect(xx-cw/2,top,cw,bh)});
function line(arr,col,width=1.5,dash=[]){ctx.strokeStyle=col;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let on=false;arr.forEach((v,i)=>{if(v==null)return;on?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v));on=true});ctx.stroke();ctx.setLineDash([])}if(state.ema20)line(e20,"#58a6ff");if(state.ema50)line(e50,"#f2bd54");if(state.ema200)line(e200,"#c084fc");if(state.bb){line(bbu,"#78909c",1,[4,4]);line(bbl,"#78909c",1,[4,4])}
let a=analyze(state.data);if(a.support){line(Array(data.length).fill(a.support),"#25c99a",1,[6,5])}if(a.resistance){line(Array(data.length).fill(a.resistance),"#ff6675",1,[6,5])}
if(state.cross){let ix=Math.max(0,Math.min(data.length-1,Math.floor((state.cross.x-pad.l)/(plotW/data.length)))),d=data[ix];ctx.strokeStyle="#536273";ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(state.cross.x,pad.t);ctx.lineTo(state.cross.x,H-pad.b);ctx.moveTo(pad.l,state.cross.y);ctx.lineTo(W-pad.r,state.cross.y);ctx.stroke();ctx.setLineDash([]);$("#ohlc").textContent=`${state.ticker} · ${d.time.toLocaleString()}  O ${formatPrice(d.open)} H ${formatPrice(d.high)} L ${formatPrice(d.low)} C ${formatPrice(d.close)} V ${formatVol(d.volume)}`}else $("#ohlc").textContent=`${state.ticker} · ${state.tf} · ${state.source}`}
function formatPrice(v){if(!Number.isFinite(v))return"—";return Math.abs(v)>=100? v.toFixed(2):Math.abs(v)>=1?v.toFixed(3):v.toFixed(5)}
function formatVol(v){if(!Number.isFinite(v))return"—";if(v>=1e9)return(v/1e9).toFixed(1)+"B";if(v>=1e6)return(v/1e6).toFixed(1)+"M";if(v>=1e3)return(v/1e3).toFixed(1)+"K";return Math.round(v).toString()}
function pattern(d){let l=d.at(-1),p=d.at(-2),p2=d.at(-3);if(!l||!p)return{name:"Insufficient data",bias:0,confidence:0};let body=Math.abs(l.close-l.open),range=Math.max(1e-9,l.high-l.low),lower=Math.min(l.open,l.close)-l.low,upper=l.high-Math.max(l.open,l.close);if(p2){let b2=Math.abs(p2.close-p2.open),bp=Math.abs(p.close-p.open);if(p2.close<p2.open&&bp<Math.max(b2,body)*.45&&l.close>l.open&&l.close>(p2.open+p2.close)/2)return{name:"Morning-star reversal",bias:2,confidence:88};if(p2.close>p2.open&&bp<Math.max(b2,body)*.45&&l.close<l.open&&l.close<(p2.open+p2.close)/2)return{name:"Evening-star reversal",bias:-2,confidence:88}}
if(body/range<.1)return{name:"Doji / indecision",bias:0,confidence:74};if(p.close<p.open&&l.close>l.open&&l.open<=p.close&&l.close>=p.open)return{name:"Bullish engulfing",bias:2,confidence:90};if(p.close>p.open&&l.close<l.open&&l.open>=p.close&&l.close<=p.open)return{name:"Bearish engulfing",bias:-2,confidence:90};if(lower>body*2.2&&upper<body*1.1)return{name:"Hammer-like rejection",bias:1,confidence:78};if(upper>body*2.2&&lower<body*1.1)return{name:"Shooting-star rejection",bias:-1,confidence:78};if(body/range>.78)return{name:l.close>l.open?"Bullish marubozu / impulse":"Bearish marubozu / impulse",bias:l.close>l.open?1:-1,confidence:76};return{name:"No dominant named pattern",bias:0,confidence:46}}
function swingLevels(d,n=50){let r=d.slice(-Math.min(n,d.length)),lows=[],highs=[];for(let i=2;i<r.length-2;i++){if(r[i].low<=r[i-1].low&&r[i].low<=r[i-2].low&&r[i].low<=r[i+1].low&&r[i].low<=r[i+2].low)lows.push(r[i].low);if(r[i].high>=r[i-1].high&&r[i].high>=r[i-2].high&&r[i].high>=r[i+1].high&&r[i].high>=r[i+2].high)highs.push(r[i].high)}let last=r.at(-1)?.close||0,support=Math.max(...lows.filter(x=>x<=last),Math.min(...r.map(x=>x.low))),resistance=Math.min(...highs.filter(x=>x>=last),Math.max(...r.map(x=>x.high)));if(!Number.isFinite(support))support=Math.min(...r.map(x=>x.low));if(!Number.isFinite(resistance))resistance=Math.max(...r.map(x=>x.high));return{support,resistance}}
