const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TF={"5m":{interval:"5m",range:"5d"},"15m":{interval:"15m",range:"1mo"},"1h":{interval:"60m",range:"3mo"},"4h":{interval:"60m",range:"6mo",aggregate:4},"1D":{interval:"1d",range:"2y"},"1W":{interval:"1wk",range:"5y"}};
const BINANCE_TF={"5m":"5m","15m":"15m","1h":"1h","4h":"4h","1D":"1d","1W":"1w"};
const state={data:[],view:90,offset:0,tf:"1D",ticker:"QQQ",source:"demo",ema20:true,ema50:true,ema200:false,bb:false,volume:true,macd:true,drag:false,lastX:0,cross:null,watch:JSON.parse(localStorage.getItem("co-watch")||'null')||["QQQ","SPY","SMH","GLD","BTC-USD","ETH-USD"],mtf:{},request:0};
const canvas=$("#chart"),ctx=canvas.getContext("2d");
const LIVE_CANDLES_KEY="co-live-candles";
const DEFAULT_API_BASE="http://localhost:5055";
function resolveApiBase(){try{const q=new URLSearchParams(location.search).get("api");if(q){const v=q.trim().replace(/\/$/,"");localStorage.setItem("co-api-base",v);return v}const stored=localStorage.getItem("co-api-base");if(stored)return stored.replace(/\/$/,"");const el=$("#apiBase");if(el&&el.value.trim())return el.value.trim().replace(/\/$/,"")}catch(e){}return DEFAULT_API_BASE}
function setProviderChip(name){const el=$("#providerChip");if(!el)return;const label=name||"—";el.textContent=label;el.className="providerChip";const key=(label||"").toLowerCase();if(key.includes("alpaca"))el.classList.add("on","alpaca");else if(key.includes("twelve"))el.classList.add("on","twelvedata");else if(key.includes("binance"))el.classList.add("on","binance");else if(key.includes("yahoo"))el.classList.add("on","yahoo");else if(key.includes("csv"))el.classList.add("csv");else if(key.includes("demo"))el.classList.add("demo");else if(label!=="—")el.classList.add("on")}
async function proxyReachable(base){try{const r=await fetch(base+"/api/health",{method:"GET",cache:"no-store"});if(!r.ok)return false;const j=await r.json();return !!j.ok}catch(e){return false}}
async function fetchProxyCandles(symbol,tf,base){const u=`${base}/api/candles?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(tf)}&provider=auto&limit=500`;const r=await fetch(u,{cache:"no-store"});let j=null;try{j=await r.json()}catch(e){j=null}if(!r.ok)throw Error((j&&(j.message||j.error))||`Proxy ${r.status}`);const rows=validRows((j.candles||[]).map(c=>({time:new Date(c.time),open:+c.open,high:+c.high,low:+c.low,close:+c.close,volume:+c.volume||0})));if(rows.length<5)throw Error("Proxy returned too few candles");const prov=j.provider==="alpaca"?"Alpaca":j.provider==="twelvedata"?"Twelve Data":(j.provider||"Proxy");return{data:rows,provider:prov}}
const status=(text,kind="")=>{const e=$("#dataStatus");e.textContent=text;e.className="status "+kind};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function seeded(seed){let x=seed||1;return()=>((x=Math.imul(1664525,x)+1013904223>>>0)/4294967296)}
function seedData(n=320,start=100,seed=19){const rnd=seeded(seed),a=[];let p=start;for(let i=0;i<n;i++){let drift=i<75?.18:i<145?-.09:i<225?.22:.03,noise=(rnd()-.5)*2.15,o=p,c=Math.max(5,o+drift+noise),h=Math.max(o,c)+rnd()*1.5,l=Math.min(o,c)-rnd()*1.5,v=450000+rnd()*1550000;p=c;a.push({time:new Date(Date.now()-(n-i)*864e5),open:o,high:h,low:l,close:c,volume:v})}return a}
function ema(data,p,field="close"){let k=2/(p+1),out=[],v=Number(data[0]?.[field])||0;for(const d of data){v=(Number(d[field])||0)*k+v*(1-k);out.push(v)}return out}
function sma(vals,p){let out=Array(vals.length).fill(null),sum=0;for(let i=0;i<vals.length;i++){sum+=Number(vals[i])||0;if(i>=p)sum-=Number(vals[i-p])||0;if(i>=p-1)out[i]=sum/p}return out}
function stdev(vals,p){let out=Array(vals.length).fill(null);for(let i=p-1;i<vals.length;i++){let s=vals.slice(i-p+1,i+1),m=s.reduce((a,b)=>a+b,0)/p;out[i]=Math.sqrt(s.reduce((a,b)=>a+(b-m)**2,0)/p)}return out}
function bollinger(data,p=20,m=2){let c=data.map(x=>x.close),mid=sma(c,p),sd=stdev(c,p);return{mid,upper:mid.map((x,i)=>x==null?null:x+m*sd[i]),lower:mid.map((x,i)=>x==null?null:x-m*sd[i])}}
function rsi(data,p=14){let out=Array(data.length).fill(null),g=0,l=0;if(data.length<=p)return out;for(let i=1;i<=p;i++){let d=data[i].close-data[i-1].close;d>=0?g+=d:l-=d}g/=p;l/=p;out[p]=100-100/(1+g/(l||1e-9));for(let i=p+1;i<data.length;i++){let d=data[i].close-data[i-1].close;g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=100-100/(1+g/(l||1e-9))}return out}
function atr(data,p=14){let tr=data.map((d,i)=>i?Math.max(d.high-d.low,Math.abs(d.high-data[i-1].close),Math.abs(d.low-data[i-1].close)):d.high-d.low);return sma(tr,p)}
function macdCalc(data){let e12=ema(data,12),e26=ema(data,26),line=e12.map((x,i)=>x-e26[i]),fake=line.map(x=>({close:x})),signal=ema(fake,9),hist=line.map((x,i)=>x-signal[i]);return{line,signal,hist}}
function aggregate(data,n){let out=[];for(let i=0;i<data.length;i+=n){let g=data.slice(i,i+n);if(!g.length)continue;out.push({time:g[0].time,open:g[0].open,high:Math.max(...g.map(x=>x.high)),low:Math.min(...g.map(x=>x.low)),close:g.at(-1).close,volume:g.reduce((a,x)=>a+(x.volume||0),0)})}return out}
function validRows(a){return a.filter(x=>x.time instanceof Date&&!isNaN(x.time)&&[x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function cryptoSymbol(s){const m={"BTC-USD":"BTCUSDT","ETH-USD":"ETHUSDT","SOL-USD":"SOLUSDT","BNB-USD":"BNBUSDT","XRP-USD":"XRPUSDT"};return m[s]||(/^[A-Z0-9]+USDT$/.test(s)?s:null)}
async function fetchBinance(symbol,tf){let bs=cryptoSymbol(symbol);if(!bs)throw Error("not crypto");let u=`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(bs)}&interval=${BINANCE_TF[tf]}&limit=500`,r=await fetch(u);if(!r.ok)throw Error(`Binance ${r.status}`);let j=await r.json();return validRows(j.map(k=>({time:new Date(k[0]),open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]})))}
async function fetchYahooHost(host,symbol,tf){let c=TF[tf],u=`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}?interval=${c.interval}&range=${c.range}&includePrePost=false&events=div%2Csplits`,r=await fetch(u,{headers:{Accept:"application/json"}});if(!r.ok)throw Error(`Market data ${r.status}`);let j=await r.json(),z=j?.chart?.result?.[0];if(!z)throw Error(j?.chart?.error?.description||"No market data returned");let q=z.indicators?.quote?.[0]||{},rows=(z.timestamp||[]).map((t,i)=>({time:new Date(t*1000),open:+q.open?.[i],high:+q.high?.[i],low:+q.low?.[i],close:+q.close?.[i],volume:+q.volume?.[i]||0}));rows=validRows(rows);return c.aggregate?aggregate(rows,c.aggregate):rows}
async function fetchMarket(symbol,tf,{preferProxy=true}={}){const base=resolveApiBase();if(preferProxy){try{if(await proxyReachable(base)){return await fetchProxyCandles(symbol,tf,base)}}catch(e){/* fall through to public providers */}}
let cs=cryptoSymbol(symbol);if(cs){try{return{data:await fetchBinance(symbol,tf),provider:"Binance"}}catch(e){}}
let last;for(const h of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{return{data:await fetchYahooHost(h,symbol,tf),provider:"Yahoo chart"}}catch(e){last=e}}throw last||Error("Market data unavailable")}
