import test from 'node:test';
import assert from 'node:assert/strict';
import '../js/local-data.js';
import {buildLevels,buildTradePlan,positionSize} from '../js/engine/scenario.js';
import {analyzeRows,exitOnBar,backtest} from '../js/backtest.js';
import {computeRSI} from '../js/engine/indicators.js';
import {validateEntry} from '../js/journal.js';
const {parseCSV,resample}=globalThis.CandleLocal;
function rows(n=120){return Array.from({length:n},(_,i)=>{const close=100+Math.sin(i/4)*4+i*.06;return {time:new Date(Date.UTC(2026,0,1,0,i*5)),open:close-.2,high:close+.6,low:close-.8,close,volume:100+i};});}
const csv=r=>'time,open,high,low,close,volume\n'+r.map(x=>[x.time.toISOString(),x.open,x.high,x.low,x.close,x.volume].join(',')).join('\n');
test('CSV handles BOM, CRLF, quotes, sorting and numeric timestamps',()=>{const input='\uFEFF'+csv(rows(30).reverse()).replace(/\n/g,'\r\n').replace('2026-01-01T00:00:00.000Z','"1767225600"');const data=parseCSV(input);assert.equal(data.length,30);assert.equal(data[0].time.toISOString(),'2026-01-01T00:00:00.000Z');});
test('CSV rejects impossible candles, duplicate dates, blank prices and invented dates',()=>{const data=rows(30);assert.throws(()=>parseCSV(csv([...data,data[0]])),/duplicate/);data[0].low=200;assert.throws(()=>parseCSV(csv(data)),/invalid/);assert.throws(()=>parseCSV(csv(rows(30)).replace(',99.8,',',,')),/missing/);assert.throws(()=>parseCSV(csv(rows(30)).replace('time,','other,')),/time\/date/);});
test('UTC aggregation preserves OHLCV and excludes incomplete bars',()=>{const data=rows(8),out=resample(data,'5m','15m',{closedOnly:true});assert.equal(out.length,2);assert.equal(out[0].open,data[0].open);assert.equal(out[0].close,data[2].close);assert.equal(out[0].high,Math.max(...data.slice(0,3).map(x=>x.high)));assert.equal(out[0].volume,303);assert.throws(()=>resample(out,'15m','5m'),/lower/);assert.equal(resample(data.slice(1),'5m','15m',{closedOnly:true}).length,1);});
test('weekly buckets start Monday UTC',()=>{const d=Array.from({length:14},(_,i)=>({...rows(1)[0],time:new Date(Date.UTC(2026,0,5+i))}));const out=resample(d,'1D','1W',{closedOnly:true});assert.equal(out.length,2);assert.equal(out[0].time.getUTCDay(),1);});
test('two selected references map exact prices and log midpoint',()=>{const c=[{top:10,bottom:90}];const levels=buildLevels(c,{}, {highPrice:400,lowPrice:100,topY:0,bottomY:100,scale:'log'});assert.ok(Math.abs(levels.priceAt(50)-200)<1e-9);assert.equal(buildLevels(c,{}, {highPrice:400,lowPrice:-1,topY:0,bottomY:100,scale:'log'}).calibrated,false);});
test('OHLC calibration remains exact after the engine truncates history',()=>{const data=rows();data[0].high=300;data[0].low=20;const {result}=analyzeRows(data);assert.ok(result.levels);const c=result.candles.at(-1);assert.ok(Math.abs(result.levels.priceAt(c.estClose)-data.at(-1).close)<1e-9);});
test('entry uses actual close and contract sizing respects ticks, increments and fees',()=>{const levels={supportY:90,resistanceY:10,calibrated:true,priceAt:y=>200-y};const plan=buildTradePlan([{range:10,mid:50,estClose:40}],levels,1);assert.equal(plan.entryY,40);const size=positionSize({accountSize:10000,riskPct:1,levels,plan,multiplier:2,quantityStep:.5,feePerUnit:1,tickSize:1});assert.ok(size.shares*size.perShareRisk<=100);assert.equal(size.shares%.5,0);assert.equal(positionSize({accountSize:-1,riskPct:1,levels,plan}),null);});
test('flat-price RSI is neutral',()=>assert.equal(computeRSI(Array.from({length:30},()=>({close:100,estClose:100}))).at(-1),50));
test('execution uses adverse opening gaps and stop-first when both touched',()=>{assert.deepEqual(exitOnBar({sign:1,stop:95,target:110},{open:90,high:115,low:89}),{price:90,reason:'both touched · stop first'});assert.deepEqual(exitOnBar({sign:-1,stop:110,target:95},{open:115,high:116,low:90}),{price:115,reason:'both touched · stop first'});});
test('replay analysis does not change when unrevealed prices change',()=>{const data=rows(),changed=rows();changed[119].close=999;const a=analyzeRows(data.slice(0,70)).result,b=analyzeRows(changed.slice(0,70)).result;assert.equal(a.conviction,b.conviction);assert.equal(a.plan.entryY,b.plan.entryY);});
test('backtest rejects costs outside supported range and runs finite results',async()=>{await assert.rejects(backtest(rows(),{feeBps:-1}),/Fees/);const result=await backtest(rows(180));assert.ok(Number.isFinite(result.netR));assert.ok(Number.isFinite(result.maxDrawdownR));for(const t of result.trades)assert.ok(new Date(t.exitTime)>=new Date(t.entryTime));});
test('journal rejects malformed entries and removes unsafe thumbnails',()=>{assert.throws(()=>validateEntry({id:'"><script>'}),/Invalid/);const e=validateEntry({id:'test',savedAt:'2026-01-01T00:00:00Z',decision:'WAIT',conviction:0,thumbnail:'https://example.com/tracker',followUp:{notes:'bad'}});assert.equal(e.thumbnail,null);assert.equal(e.followUp,null);});

test('source interval validation prevents incorrect CSV labels',()=>{assert.throws(()=>CandleLocal.validateInterval(rows(),'15m'),/closer/);assert.equal(CandleLocal.validateInterval(rows(),'5m').length,120);});
test('backtest takes real trades at next open and costs reduce returns',async()=>{const trend=Array.from({length:300},(_,i)=>{const c=100+i*.15+Math.sin(i/5)*2;return{time:new Date(Date.UTC(2026,0,1,0,i*5)),open:c-.1,high:c+.25,low:c-.3,close:c,volume:1000}});const free=await backtest(trend,{feeBps:0,slippageBps:0}),costly=await backtest(trend,{feeBps:10,slippageBps:5});assert.ok(free.trades.length>0);assert.ok(costly.netR<free.netR);for(const trade of free.trades){assert.equal(trade.entry,trend.find(r=>+r.time===+trade.entryTime).open);assert.ok(trade.r>0);}});
